variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_IMAGE_NAME_LINUX: librearp/linux-build-docker

stages:
  - build

build-linux:
  stage: build
  image: $CI_REGISTRY/$DOCKER_IMAGE_NAME_LINUX:latest
  tags:
    - linux
  script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build .
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - "build/LibreArp_artefacts"
